"""Shallow model package for MatFormer granularity refactors."""

from models.correction import (
    CorrectionContext,
    VALID_CORRECTION_MODES,
    VALID_SAMPLING_MODES,
    build_correction_context,
    build_correction_context_from_pattern,
    build_local_correction_context_from_pattern,
    derive_local_membership_pattern,
    correction_context_from_config,
    should_activate_local_correction,
    summarize_correction_context,
    summarize_correction_context_from_config,
)
from models.ffn import CatLlamaMLP, ModifiedLlamaMLP
from models.granularity import (
    MATFORMER_GRANULARITY_DISPLAY_NAMES,
    MATFORMER_GRANULARITY_ORDER,
    GranularityMetadata,
    GranularityPattern,
    build_granularity_pattern,
    canonical_prefix_fraction,
    get_block_membership_counts,
    get_concat_block_membership_counts,
    get_concat_block_membership_counts_from_metadata,
    get_concat_block_metadata,
    get_concat_gradient_membership_correction_scales,
    get_concat_gradient_membership_correction_scales_from_metadata,
    get_concat_layout_diagnostic,
    get_ffn_prefix_metadata,
    get_gradient_membership_correction_scales,
    get_granularity_metadata,
    get_prefix_membership_segment_metadata,
    granularity_block_count,
    granularity_concat_block_count,
    granularity_prefix_width,
    summarize_granularity_pattern_from_config,
    summarize_granularity_pattern,
)
from models.wiring import (
    apply_granularity_pattern_to_model,
    build_global_granularity_pattern,
    ModifiedLlamaForCausalLM,
    build_per_layer_granularity_pattern,
)

__all__ = [
    "CorrectionContext",
    "VALID_CORRECTION_MODES",
    "VALID_SAMPLING_MODES",
    "build_correction_context",
    "build_correction_context_from_pattern",
    "build_local_correction_context_from_pattern",
    "derive_local_membership_pattern",
    "correction_context_from_config",
    "should_activate_local_correction",
    "summarize_correction_context",
    "summarize_correction_context_from_config",
    "MATFORMER_GRANULARITY_DISPLAY_NAMES",
    "MATFORMER_GRANULARITY_ORDER",
    "GranularityMetadata",
    "GranularityPattern",
    "CatLlamaMLP",
    "ModifiedLlamaMLP",
    "ModifiedLlamaForCausalLM",
    "build_granularity_pattern",
    "canonical_prefix_fraction",
    "get_block_membership_counts",
    "get_concat_block_membership_counts",
    "get_concat_block_membership_counts_from_metadata",
    "get_concat_block_metadata",
    "get_concat_gradient_membership_correction_scales",
    "get_concat_gradient_membership_correction_scales_from_metadata",
    "get_concat_layout_diagnostic",
    "get_ffn_prefix_metadata",
    "get_gradient_membership_correction_scales",
    "get_granularity_metadata",
    "get_prefix_membership_segment_metadata",
    "granularity_block_count",
    "granularity_concat_block_count",
    "granularity_prefix_width",
    "summarize_granularity_pattern_from_config",
    "summarize_granularity_pattern",
    "build_global_granularity_pattern",
    "build_per_layer_granularity_pattern",
    "apply_granularity_pattern_to_model",
]
